project:
  type: website

website:
  title: "SquishTastic!!!"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com/jgeller_phd
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

